version: '3'
services:
  db:
    platform: linux/amd64
    image: postgres:${POSTGRES_VERSION}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    container_name: postgres
    networks:
      - practise

  pgadmin:
    platform: linux/amd64
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:  
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      - db
    networks:
      - practise
  
  
  app:
    platform: linux/amd64
    build: .
    command: bash -c "uvicorn app.main:app --port ${APP_PORT} --host ${APP_HOST} --reload"
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - ${APP_PORT}:${CONTAINER_PORT}
    env_file:
      - .env
    restart: unless-stopped
    container_name: app
    networks:
      - practise


volumes:
  postgresql-data:

networks:
  practise: